### ISSUE TITLE
Doesn't always give correct output

### ISSUE THREAD

**Issue by mackenzieyoung** [balaklava/cspath-datastructures-capstone-project#3]
https://github.com/balaklava/cspath-datastructures-capstone-project/blob/7c75f8d8b1aba55b975c1eeadc4a721b6d4d0a03/soho_final/script.py#L80-L86

This works for the most part, but when I typed in "cr", it just repeated "What type of food would you like to eat? Type the beginning of that food type and press enter to see if it's here." instead of saying there were no restaurant types beginning with "cr". But when I typed in "q", for example, it did work correctly.

**Comment by balaklava** [comment]
Thank you for a feed back and a clear explanation what exactly did not work.
