### ISSUE TITLE
CSD SoHo Restaurants Grade Summary

### ISSUE THREAD

**Issue by mackenzieyoung** [balaklava/cspath-datastructures-capstone-project#4]
## Rubric Score
 
### Criteria 1: Search by Word Beginning
* _Score Level:_ 3 (Meets expectations)
* _Comment(s):_ The linked list or hash map data structures have been correctly implemented. Functionality of the demoed user experience is mostly replicated, but doesn't always have correct output when there are no restaurant types that include the inputted word beginning.
  
### Criteria 2: Retrieving Restaurant Data
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ Great job, The hash map of linked lists structure has been correctly implemented, and the restaurant data is presented in a user friendly way.
 
### Criteria 3: Overall Code Quality and Functionality
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ Good, the example user experience has been replicated and improved upon in some way. The code follows proper Python conventions, is clean, clear, and easy to read. Especially nice use of comments.

### Criteria 4: Presentation
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ Good, your presentation accurately describes​ the data structures used and corresponding runtimes. Presentation extends beyond this project​ and describes how data structures could be used to build other interesting projects. Some small typos.
 
### Overall Score: 15/16
Nice job overall! The search by word beginning part has some small issues, but in general, it works correctly and is user friendly.

**Comment by balaklava** [comment]
Thank you for the code review.
